import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Link from "next/link";

import { NextIntlClientProvider } from "next-intl";
import {getMessages} from 'next-intl/server';

import "../../style/global.css";
import style from "../../style/layout.main.module.css";

import StoreProvider from "@/components/StoreProvider";

const robotoSans = Roboto({
  weight: ["400"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


type Props = {
  children: React.ReactNode;
  params: {locale: string};
};


export default async function RootLayout({children, params}: Props) {

  const { locale } = params
  console.log(locale);
  
  const messages = await getMessages({locale: params.locale});
  console.log(messages);

  return (
    <html lang={locale}>
      <body className={robotoSans.className}>

          <StoreProvider>

            <div className={style.contenire}>
              <div className={style.content}>

                {/* locale={locale} */}
                <NextIntlClientProvider messages={messages}>
                  { children }
                </NextIntlClientProvider>


              </div>
            </div>
            
          </StoreProvider>
      </body>
    </html>
  );
}
