import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Link from "next/link";

import "../style/global.css";
import style from "../style/layout.main.module.css";

import StoreProvider from "@/components/StoreProvider";

const robotoSans = Roboto({
  weight: ["400"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  
  return (
    <html lang='en'>
      <body className={robotoSans.className}>

          <StoreProvider>

            <div className={style.contenire}>
              <div className={style.content}>

                { children }

              </div>
            </div>
            
          </StoreProvider>
      </body>
    </html>
  );
}
